### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [isthisstackoverflow/noop#1]
Hello, just tried this code  but i cant seem to get a valid result.

Can you add some comments, so I can understand it better?
I suspect the issue lies on my side.

Thx.
Batman

**Comment by isthisstackoverflow** [comment]
Hi there.

Sure, some documentation will be added, and I'm planning to release the package so npm soon-ish. What have you tried to do and what didn't work?

Your answers will help me improving the package.

**Comment by isthisstackoverflow** [comment]
It's now published to NPM. https://www.npmjs.com/package/@underdash/noop

Try installing from there. Does this resolve your problem?

**Comment by isthisstackoverflow** [comment]
Since you effectively noop(myQuestions), I assume the problem is solved.
